/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Blog: typeof import('./components/Blog.vue')['default']
    CallToActionBtn: typeof import('./components/CallToActionBtn.vue')['default']
    CiCloseBig: typeof import('~icons/ci/close-big')['default']
    CiMenuAlt02: typeof import('~icons/ci/menu-alt02')['default']
    CiWarningOutline: typeof import('~icons/ci/warning-outline')['default']
    Correlacao: typeof import('./components/Correlacao.vue')['default']
    DigitalTransformation: typeof import('./components/DigitalTransformation.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Form: typeof import('./components/Form.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    NavDrawer: typeof import('./components/NavDrawer.vue')['default']
    Partners2: typeof import('./components/Partners2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceNow: typeof import('./components/ServiceNow.vue')['default']
    Services: typeof import('./components/Services.vue')['default']
    SuccesCases: typeof import('./components/SuccesCases.vue')['default']
    Team: typeof import('./components/Team.vue')['default']
    WhyEdx: typeof import('./components/whyEdx.vue')['default']
  }
}
